annotations:
  application.giantswarm.io/team: planeteers
chartApiVersion: v2
chartFile: mcp-prometheus-0.1.74-ae240199274bcb5d591787b728d4e9caed1f823e.tgz
dateCreated: '2026-06-01T15:56:30.415017Z'
digest: e754110d25efdbb76f0df43e7936a4d8f771154a2671185a312c50d766244e39
home: https://github.com/giantswarm/mcp-prometheus
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
