annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: alertmanager-to-github-0.2.1-018e9154b71ec32b9cb371d7513fe7223e48fae1.tgz
dateCreated: '2026-04-24T13:43:26.659860Z'
digest: 291227f93006105dd92bd983a570c8882dc4cdee4855348d04a528c1493af8f1
home: https://github.com/giantswarm/alertmanager-to-github-app
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
