annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-20.2.0-b5aae05d9849746896134d8e3d9d2be2d7161919.tgz
dateCreated: '2026-05-12T21:43:49.968942Z'
digest: 30fad2497a82cbaa1cc2bae25e286b1c042183790352bc9ce6c7d360840ca1bf
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
