annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: alertmanager-to-github-0.2.2-dev.fix-appversion.2026-06-16.14-10-12.ha73cda8.tgz
dateCreated: '2026-06-16T14:10:51.552255Z'
digest: 1fb9ac111c730adb28c051e9c9647d9388b1073c724e55243b9adf805e73747f
home: https://github.com/giantswarm/alertmanager-to-github-app
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
