annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-20.2.0-b8528738de4d0015db47c04d9827ea3aa760dc03.tgz
dateCreated: '2026-04-27T06:06:39.567736Z'
digest: 530ea0ec8c2aacee47f8f94d7036de1ebda1d8c097027ad4b291be7a205923cf
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
