annotations:
  application.giantswarm.io/team: planeteers
chartApiVersion: v2
chartFile: mcp-prometheus-0.2.8-dev.remove-auto--m-lint-yaml.2026-06-10.07-49-21.h541d348.tgz
dateCreated: '2026-06-10T07:58:43.346184Z'
digest: d9880024d8a02ae962ef1e1b471189c8a1c71078e9f448431b606a2d6761f5aa
home: https://github.com/giantswarm/mcp-prometheus
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
