annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-20.2.0-448f35dc117f655f233f3cccd7f4d384d41fc45f.tgz
dateCreated: '2026-03-25T21:13:48.726907Z'
digest: 931298ecf2cccc5785a8fd7ff3dafcb8b16f4deacc7f9974cfebb0953a3ac722
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
