annotations:
  application.giantswarm.io/team: planeteers
chartApiVersion: v2
chartFile: mcp-prometheus-0.0.37-90f27b5677a2c66ad473327cfdf986b3a7eb86f3.tgz
dateCreated: '2026-03-10T09:34:32.742192Z'
digest: cbea5f5426651d8769899d7a43b4b07607d1976be41ae20b3758cbde4896b40b
home: https://github.com/giantswarm/mcp-prometheus
icon: https://github.com/prometheus/prometheus/raw/main/documentation/images/prometheus-logo.svg
