annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-20.0.0-5c0242d89ed9ea97ae84d73f9e46fb3f2b659f90.tgz
dateCreated: '2026-05-22T06:27:24.425751Z'
digest: 7204da4071c67fea1fdfe8322e01764e5e0c30872d423db12772222e41e2743d
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
