annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-19.0.2.tgz
dateCreated: '2026-02-12T14:30:04.381734Z'
digest: 29d1abac8bacd7e961b68b13cd5e1289e41296c2760df89882de1a0158db371b
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
