annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-21.0.2-dev.main-release-minor.2026-06-29.13-00-33.hd308ddd.tgz
dateCreated: '2026-06-29T13:01:55.070760Z'
digest: 91faa134a8cccff135ef3879183873a545cc2cfe85b0c4a628f0b5d397e692ef
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
