annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-20.0.0-99b6a955ba50c6c360f4997718e98f14e22340c9.tgz
dateCreated: '2026-04-15T11:48:37.344294Z'
digest: f4b0a1d8571e3d80a1cb3af7f756cfe99cb7a8d52657225cbd48ea633708c086
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
