annotations:
  application.giantswarm.io/team: atlas
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: !!python/object/new:app_build_suite.build_steps.helm_consts.BlockLiteralStr
  - "- name: Support\n  url: https://github.com/giantswarm/prometheus-operator-crd/issues\n\
    - name: Upstream project\n  url: https://github.com/prometheus-community/helm-charts\n"
chartApiVersion: v2
chartFile: prometheus-operator-crd-22.0.1-dev.renovate-p--r-crds-30-x.2026-07-31.10-07-08.h277f72a.tgz
dateCreated: '2026-07-31T10:07:44.908735Z'
digest: 87ce0ece114ceffbf66f3c7c1efacaf001b87a64ed3a745a26491080a654eec7
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
