annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-21.0.1-dev.renovate-actions-checkout-6-x.2026-06-02.20-53-59.tgz
dateCreated: '2026-06-02T20:54:33.471225Z'
digest: 4617a3f6b925d3bb473ebd7f692c2955ba88219c5339b8eada3819c19b425cb5
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
