annotations:
  application.giantswarm.io/team: planeteers
chartApiVersion: v2
chartFile: mcp-prometheus-0.0.46-36277a5bc064a2a6957bb5fe7f494a9d8b9ea6d7.tgz
dateCreated: '2026-03-17T23:53:18.684813Z'
digest: c3fe5fe0d9e324ad295acd25fcf21ed1d0da354e80166b0d31d1d77c0a031ef7
home: https://github.com/giantswarm/mcp-prometheus
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
