annotations:
  application.giantswarm.io/team: planeteers
chartApiVersion: v2
chartFile: mcp-prometheus-0.1.63-7feb68a0fd3938716974043f827dd2ab5ed7920f.tgz
dateCreated: '2026-05-25T13:52:35.179612Z'
digest: ec2e6ebbe47f26f54aecb09b351f0fa8c5722cd8a3ea51fde6788f0a53b6fbe9
home: https://github.com/giantswarm/mcp-prometheus
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
