annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-20.2.0-d5b746022aae7dce3d51d779a0aef40dcfe0ef6e.tgz
dateCreated: '2026-05-17T17:32:40.161651Z'
digest: 53b2db6ff7c70e6b63262468273a7d81957e3458de02e30d9a4e9c2650b47b4f
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
