annotations:
  application.giantswarm.io/team: atlas
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: !!python/object/new:app_build_suite.build_steps.helm_consts.BlockLiteralStr
  - "- name: Support\n  url: https://github.com/giantswarm/kube-prometheus-stack-app/issues\n\
    - name: Upstream project\n  url: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack\n"
chartApiVersion: v2
chartFile: kube-prometheus-stack-24.0.1-rf6c957b0t20261005160534hcd430ad.tgz
dateCreated: '2026-10-05T16:10:19.446037Z'
digest: 285680299f1c5b28aa20f60677da7ca9dec4a0174381b109e8ceb0403d958e76
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
