annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-20.2.0-ec6fd2ac92c721c6a404e86b7ca780e00a5c5c6a.tgz
dateCreated: '2026-04-15T11:54:49.410723Z'
digest: c3436a34ac91a69fceed2bacb5aa9184800867d402ffc10bc55362fe79004097
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
