annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-20.2.0-a21957d0474175b57303ac55c0348d18a27b5711.tgz
dateCreated: '2026-04-27T15:55:21.038366Z'
digest: 5c7fa753b4da82e67b124ba1dec433a4d15eb774524e5fcb7a309289693e0302
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
