annotations:
  application.giantswarm.io/team: planeteers
chartApiVersion: v2
chartFile: mcp-prometheus-0.2.2-dev.renovate-golang-org-x-sync-0-x.2026-06-08.14-20-18.tgz
dateCreated: '2026-06-08T14:30:55.021969Z'
digest: c93ea580b89e95078e8457d116a0787f6ec83386b42b65ce69cab16a9bbc2723
home: https://github.com/giantswarm/mcp-prometheus
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
