annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-20.0.0-8310cf38d91861e7af0a2f1c16fce215aab33a59.tgz
dateCreated: '2026-03-04T13:31:00.516126Z'
digest: 4a2c5f9c06569ac38665af2a60587cf7f8f5edd3e938f7d376566b6512980a9b
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
