annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-19.0.1.tgz
dateCreated: '2026-02-12T15:35:54.463960Z'
digest: 82e7b89f8992c41c0835eaeebe0a2fc55ca1d523f45e313bb3be4504bd75dce5
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
