annotations:
  application.giantswarm.io/team: atlas
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: !!python/object/new:app_build_suite.build_steps.helm_consts.BlockLiteralStr
  - "- name: Support\n  url: https://github.com/giantswarm/kube-prometheus-stack-app/issues\n\
    - name: Upstream project\n  url: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack\n"
chartApiVersion: v2
chartFile: kube-prometheus-stack-23.0.1-dev.main.2026-09-15.16-29-15.h347ae34.tgz
dateCreated: '2026-09-15T16:30:12.940736Z'
digest: d1d7b09209121396fafa93836cf09a0fe638b6eaedcf436e35341695bb30837e
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
