annotations:
  application.giantswarm.io/team: atlas
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: !!python/object/new:app_build_suite.build_steps.helm_consts.BlockLiteralStr
  - "- name: Support\n  url: https://github.com/giantswarm/kube-prometheus-stack-app/issues\n\
    - name: Upstream project\n  url: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack\n"
chartApiVersion: v2
chartFile: kube-prometheus-stack-23.0.1-dev.teams-alignment-branch.2026-09-04.16-11-44.h51429f3.tgz
dateCreated: '2026-09-04T16:12:38.742498Z'
digest: 301f6d89655f0e7380f1362a93493551081e259765593e4818fe4c875e35b9a5
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
