annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-21.0.1-dev.renovate-architect-9-x.2026-06-18.02-46-47.hf386377.tgz
dateCreated: '2026-06-18T02:47:49.661240Z'
digest: 596b47f16c0653f11505e96bc30d16a9d6350d7000fd0aa76a8c668ff46b4e3a
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
