annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-22.0.1-dev.renovate-k--stack-88-x.2026-08-04.16-56-40.hd15a5d7.tgz
dateCreated: '2026-08-04T16:57:17.878462Z'
digest: 922068dfd8974ff272c73a755d6783ab518fcf696659eddde808e38029158d20
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
