annotations:
  application.giantswarm.io/team: planeteers
chartApiVersion: v2
chartFile: mcp-prometheus-0.0.19-70c12b448131ab3e97374216d49728a5750e9664.tgz
dateCreated: '2026-03-03T09:46:30.863070Z'
digest: 14726d172465abdef02d60845eb6fde40fbddf01508c98b8babe912119153be0
home: https://github.com/giantswarm/mcp-prometheus
icon: https://github.com/prometheus/prometheus/raw/main/documentation/images/prometheus-logo.svg
