annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-21.0.1-dev.renovate-architect-9-x.2026-06-03.18-02-20.tgz
dateCreated: '2026-06-03T18:03:00.143515Z'
digest: 4bfd7d86e10460c1dae7732b53d2afd9db268f166ffb2696212eb4591d613319
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
